# Generated by Django 3.1.1 on 2020-09-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Requests",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rtype",
                    models.CharField(
                        choices=[
                            ("GET", "Get"),
                            ("POST", "Post"),
                            ("PUT", "Put"),
                            ("DELETE", "Delete"),
                        ],
                        max_length=7,
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("comment", models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
